### ISSUE TITLE
Is there a way to unload a target?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#101]
I see the Origen.app.unload_target! method exists but it doesn't seem to do the hard unload.  Is that because it is just expected that once a user uses origen they would just cycle through targets?

**Comment by ginty** [comment]
This should be a stack overflow question.

I don't know of a case where a user app would need to unload the target, normally you would want to either keep the one you have or change to another one.

The unload_target! method is marked as a private API since it is not intended for application use and is used to set up some specific test scenarios.

**Comment by info-rchitect** [comment]
ok thanks
