### ISSUE TITLE
Running $dut init multiple times during program flow creation

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#114]
Hi,

I am seeing Origen re-init the $dut model 3 times when I try to create a very simple test program flow.

~~~shell
peologin02:ppekit $ origen p ws1.rb
[WARNING]    0.015[0.015]    || PPEKit: Metadata type 'mbist' has an invalid source
[WARNING]    0.015[0.001]    || PPEKit: Metadata type 'scan' has an invalid source
[INFO]       0.045[0.020]    || PPEKit: Loading IP and registers from /users/user1/origen/ppekit/vendor/mycompany/myprod/a0/origen_src/top_level.rb
[INFO]       3.081[3.035]    || PPEKit: Loading of IP and registers complete
[INFO]       3.081[0.000]    || PPEKit: Loading fuses from /users/user1/origen/ppekit/tmp/myprod_a0_fuses.yml
[INFO]       6.414[0.001]    || PPEKit: Loading of fuses complete
[INFO]       6.414[0.000]    || Pinnacle: Loading pins from /users/user1/origen/ppekit/tmp/myprod_a0_pins.yml
[INFO]       14.610[5.321]   || Pinnacle: Loading of pins complete
[INFO]       14.610[0.000]   || PPEKit: myprodel A0 model accessible as '$dut'
[INFO]       14.734[0.124]   || **********************************************************************
[WARNING]    14.817[0.082]   || PPEKit: Metadata type 'mbist' has an invalid source
[WARNING]    14.817[0.000]   || PPEKit: Metadata type 'scan' has an invalid source
[INFO]       14.850[0.020]   || PPEKit: Loading IP and registers from /users/user1/origen/ppekit/vendor/mycompany/myprod/a0/origen_src/top_level.rb
[INFO]       16.571[1.720]   || PPEKit: Loading of IP and registers complete
[INFO]       16.571[0.001]   || PPEKit: Loading fuses from /users/user1/origen/ppekit/tmp/myprod_a0_fuses.yml
[INFO]       20.439[0.002]   || PPEKit: Loading of fuses complete
[INFO]       20.439[0.000]   || Pinnacle: Loading pins from /users/user1/origen/ppekit/tmp/myprod_a0_pins.yml
[INFO]       29.200[5.549]   || Pinnacle: Loading of pins complete
[INFO]       29.200[0.000]   || PPEKit: myprodel A0 model accessible as '$dut'
[INFO]       29.283[0.082]   || Generating... ws1.rb

Frame number: 0/25

From: /users/user1/origen/ppekit/program/components/_jtag.rb @ line 1 :

 => 1: binding.pry
    2: Flow.create do |options|
    3:
    4:   binding.pry
    5:   func :test1, bin: 10, id: :t1
    6:

[1] pry(main)>
[WARNING]    41.590[12.308]  || PPEKit: Metadata type 'mbist' has an invalid source
[WARNING]    41.591[0.000]   || PPEKit: Metadata type 'scan' has an invalid source
[INFO]       41.618[0.017]   || PPEKit: Loading IP and registers from /users/user1/origen/ppekit/vendor/mycompany/myprod/a0/origen_src/top_level.rb
[INFO]       43.982[2.364]   || PPEKit: Loading of IP and registers complete
[INFO]       43.982[0.000]   || PPEKit: Loading fuses from /users/user1/origen/ppekit/tmp/myprod_a0_fuses.yml
[INFO]       48.005[0.002]   || PPEKit: Loading of fuses complete
[INFO]       48.006[0.000]   || Pinnacle: Loading pins from /users/user1/origen/ppekit/tmp/myprod_a0_pins.yml
[INFO]       57.473[6.184]   || Pinnacle: Loading of pins complete
[INFO]       57.474[0.000]   || PPEKit: myprodel A0 model accessible as '$dut'

Frame number: 0/32

From: /users/user1/origen/ppekit/program/components/_jtag.rb @ line 4 :

    1: binding.pry
    2: Flow.create do |options|
    3:
 => 4:   binding.pry
    5:   func :test1, bin: 10, id: :t1
    6:
    7: end
~~~

It doesn't seem like the expected behavior given that it incurs a large performance penalty.

**Comment by ginty** [comment]
We can probably optimize to get rid of the redundant multiple loads before the first flow is executed, I believe we already did a similar thing for the pattern generation side of things a while back.

However, the reality is that when generating a test program your target is going to be re-loaded many times, basically every time it hits `Flow.create` in either a top-level flow module or an imported sub-module.

That is by design as what we found in earlier incarnations of Origen, was that when people could use a common DUT instance to pass information between flows and to sub-flows, it started to build in an un-intended order dependence on how the flows were generated. i.e. Some flows would only generate correctly if the DUT had been setup with some state from a previous flow. In the best case it would crash, in the worst case it would generate OK but with the wrong flow content.

To stop that we enforced a re-load of the DUT between flows so that it could not be used to carry flow configuration information, forcing the user then to pass configuration parameters on the flow import line which is always repeatable/deterministic.

Therefore the real issue here is really the long target load times and we should look at why that is the case.
Perhaps there are better coding patterns/architecture we can advise you on, or perhaps there is some area of Origen that we need to speed up.
Can you provide more info on what is making the target load time long?

**Comment by info-rchitect** [comment]
thanks Ginty.  It is just the size of the chip, the register init from .rb files takes just under 2 seconds (not bad) but the pins init takes 5+ seconds.  This is because the pins hash (2000+ pins) is stored as YAML versus native Ruby.  I just haven't gotten around to writing the exporter to native Ruby for pins.  In the meantime I could Marshal it as a binary to improve the speed.  So lets say I get it to ~4 seconds per init.  We will have ~30 sub-flows, so this will be an ~2 minute penalty.  Of course, I understand the need for robustness of the flow generation, but any performance improvements will be greatly appreciated.

Also, I am logging quite a bit of information, is there a way to dynamically suppress the logging during the subsequent loads? 

thx

**Comment by ginty** [comment]
Ok @info-rchitect, I think we should be able to get your target load time down to almost instant.
I have written a proposal here, please review and feedback if you fancy taking on the implementation of it: https://github.com/Origen-SDK/rfcs/pull/4
That PR is the place to comment if we need to have further discussion on it.

For the logging, I'm really not a fan of superfluous logging, and in my opinion almost all logging should be done via `Origen.log.debug 'some info you might need when debugging'`.
Then you won't see it in normal operation, but if you run with the `-d` switch you will.

**Comment by info-rchitect** [comment]
reviewing now, thx!
