### ISSUE TITLE
Need an equivalent of the sub_block API for non-silicon models

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/origen#141]
This is a continuation of the discussion started here: https://stackoverflow.com/questions/46669289/convention-for-passing-arguments-to-non-silicon-subblocks-helpers

@coreyeng wrote:

@ginty What would you think of a 'component' API. 

For example, we could have:

~~~ruby
# components.rb
component(:scan, TIPScan::ScanTester,
  # options
  wgl_dir: ..., # defaults to Origen.app.root/pattern/wgl
  custom_sort: proc do {\|wgl_name\| ...},
)

# then we can do things like:

$dut.scan #=> TIPScan instance
$dut.component(:scan) #=> same as above
$dut.components #=> [TIPScan instance, ...]
$dut.has_component(:scan) #=> true etc.
~~~

Pretty much just a stripped down subblock class to handle these. I think our IAR/C compilers and even CATI could benefit from this and make the setup cleaner and more customizable.

**Comment by ginty** [comment]
@coreyeng, I like the direction this is heading.

I like the distinction between the sub_block API which should be used to model things which are physical silicon blocks, and JTAG and all other similar plugins should transition over to that in time, and then we have this new one which is used to plug in more abstract things.

I wonder if `service` is more descriptive than `component` ?

I think we should also align to the conventions in the `sub_block` API, so it would be:

~~~ruby
service :scan, class_name: "TIPScan::ScanTester", other: options
~~~

**Comment by info-rchitect** [comment]
We created our own custom TestModules class to handle a similar concept. Because we don't use Origen to create patterns (yet), we needed a model to house the test method parameters specific to various types of test such as scan

**Comment by info-rchitect** [comment]
@ginty I think the API should allow a block definition similar to the new PowerDomains module.

**Comment by coreyeng** [comment]
@ginty Yes, I tried to keep it similar to the sub_block API. I typed it out manually though so I just forgot the class_name option and put it as an argument.

What I was actually thinking of is trying to have sub_block inherit from component and open up the component class to be easily pulled in by other stuff too. This way, sub_block is really just a component with some added features. Then, we could open up more if it comes up. For example, I thought about even adding a 'compiler' one for NXP, for example:

~~~
compiler(:iar_m4_core0, class_name: IarPatgen, options)
compiler(:iar_m0_core1, class_name: IarPatgen, options)
compiler(:gcc_m4_core0, class_name: ARMCompiler, options)
compiler(:gcc_m0_core1, class_name: ARMCompiler, options)
compiler(:espresso, class_name: MCUEspresso, options) # handles both cores
~~~

All the compiler class would need to do is include Origen::Components (for inherit, haven't actually looked much into it yet so don't know which way to go yet) and then you'd just get stuff like:

~~~
dut.compilers #=> [:iar_m4_core0, iar_m0_core1, :gcc_m4_core0, :gcc_m0_core1, :espresso]
etc. etc. etc.
~~~

all for free. The the compiler can add anything extra it needs (take a RAM location base for example, like sub_blocks :base_address). Or I can add some feature to take the core as an option and then have:

~~~
$dut.compilers.core1 #=> [:iar_m0_core1, :gcc_m0_core1, :espresso]
~~~

Obviously, just an example, but my idea is creating a more open 'component' class then have sub_block be a child of that.

Long way of saying that's why I choose 'component'. I think 'service' doesn't fit the definition of the above as closely, but I could make a 'service' class that inherits from 'component' for these instead of using 'component' directly. What do you think?

@info-rchitect I think that if we go with as I proposed above then we should stick with the way sub_block works now, with options. That said, I could look into allowing for both, so that you could pass a block to it as well then class itself is responsible for figuring out what to do. I think that will open up a lot of discrepancies though. For example, we'd have to figure out what the class should do if one app gives it:

~~~
component(:scan, class_name: TIPScan::ScanTester, wgls: 'patterns/wgl')
~~~

and another one gives it:

~~~
component(:scan) do
  class_name = TIPScan::ScanTester
  wgls: 'pattern/wgl'
end
~~~

Though, we already do it for registers and bitfields so I don't see why we couldn't do it here too. I've just always used option hashes.

**Comment by ginty** [comment]
@coreyeng, that all sounds good.

One of the main reasons I didn't initially like the name `component` is because that is the name I usually give to test program sub-flows in my apps. However, upon reflection I see that this is just a convention I have used within my own apps and is nothing official, so I'm fine to go with `component` if you want to.

On the supporting block args, this is the form we should support for consistency:

~~~ruby
component :scan do |c|
  c.class_name = TIPScan:ScanTester
  c.wgls = 'pattern/wg1'
end
~~~

It would be trivial to add support for that API (and the original option hash approach) by using the `Collector` class as per this example:
https://github.com/Origen-SDK/origen/blob/703f32108dc4bb559de5a6670fb97578266ba935/lib/origen/registers.rb#L90

**Comment by coreyeng** [comment]
I'm not really attached to the name 'component', I just didn't think 'service' fit the broader definition. If 'component' already has its use, I could go with 'accessory', 'peripheral', or 'element'. Or could go with 'constituent', which is direct synonym for 'component, but that word isn't as common. What do you think of any of those?

**Comment by info-rchitect** [comment]
between component and service i choose component.  all it really is is an arbitrary container of data in an object orientated programming language.  rectangle o' stuff is applicable but probably won't work.

**Comment by info-rchitect** [comment]
@coreyeng any timeline on adding this?

**Comment by ginty** [comment]
I forgot about this thread, but upon re-reading it I still think that 'service' is the right term for what is being described here.

It is not really a model, since a model generally refers to an object that represents something in the physical domain. "component" to me is close to an alias of a model, or at least makes me think of something related to the physical BOM of the DUT.

It's more like a helper, or indeed a service, that is being bolted on to help you test the DUT. "helper" though, makes me think of something smaller, a single method or so, whereas "service" makes me think of a much more substantial piece of functionality that is being made available to the DUT.

**Comment by coreyeng** [comment]
@info-rchitect Not really. I've just been working on it in my spare time (which hasn't been much recently), but I've definitely started it and have completed a decent amount. At the rate things are going though, probably need a few more weeks. The main driver I had for it already works as a subblock, it just looks kind of funny as one. Are you looking to try to use this soon?

**Comment by info-rchitect** [comment]
@coreyeng I have a couple ideas regarding this concept but currently created a TestModules class to better align with our internal test methods.  there seems to be a fine line between a Controller and this object.

**Comment by coreyeng** [comment]
Hello,

This is taking far longer than I thought it would (probably because it doesn't help so much with getting parts out the door, so hard to justify putting much time into it day by day) so making a placeholder to review until its ready for a real  PR.

I'm not sure how to reference a commit, let alone a commit on fork, but here is the project:
https://github.com/coreyeng/origen/tree/components

Currently, I've implemented what my original view of this issue would be. This comes in the form of a 
protologism, Componentable, taking after Ruby's Enumerable mix-in. My goal with this is to very quickly, easily, and fluidly allow for any class to be 'component-ized'. The result looks very similar to a basic subblock interface: basically a way to add, delete, and retrieve items in to and out of the some container. By including Componentable, the new class automatically has a bunch of utility methods for adding, moving, removing, deleting, and some basic querying.

This comes to fruition with components, which is automatically added to all Origen::Model inheritors. Using componentable, creating a generic container and giving it and its parents all the utilities it needs was as simple as just saying 'include Origen::Componentable' and moving on. If you look at that class, that's literally almost all it is (with a comment explaining the only other line).

This is what I was going for. Now, if I want to add something like 'compilers', 'ramloaders', etc., I can include Componentable, then focus on what makes these unique. 

Furthermore, any enhancements or bugfixes will reach all of the 'Componentable' objects without any extra work..

I'm sharing this earlier because just putting this interface together took more time than I thought it would and I want to have the interface reviewed before I spent the effort trying to transition SubBlocks, Tests, and Fuses over to use this. So please take a look and let me know what you think. I'm going to start transitioning SubBlocks over to just be a more complex Component and anything that I may have missed in the SubBlock interface that seems useful for all components may get moved over. Other than that, the only other enhancements I have are:

* delete should also delete the method on the parent
* add checks for methods that may step on each other

So, please let me know of any other requests.

I have a full spec written, documentation covering generic Components from an Origen::Model perspective, an advanced topic on creating custom Componentable objects, and the Componentable API documented in Yardoc (this last one still needs some work though, but should be good enough for an informal review). The docs have some ugly red lines in them, but those are just notes for me to finish/fix things. I still think its in a decent place though.

I currently have specs forced to only run componentable and subblocks. So if you pull down the commit and see that most of the specs are gone, that's why. The failing specs are just for another feature I've been working on in the same workspace that I'll discuss later. All the original Origen specs pass.

I have two other things in this: First, I added an origen_model_init callback to help with booting. Though, now I'm thinking I can probably just use |= to initialize, but I haven't done that yet and I don't intend to remove origen_model_init since I think it still has use, provided it doesn’t slow down Origen (I didn't notice it doing so). 

I also added an unrelated change to remotes where it displays the name of the current remotes. I forgot where (the only) remote we have was at and it was having trouble populating since we relocated one of the systems. This just does the following, but can be nice in keeping track of what plugins are actually pulling in which remotes.

![image](https://user-images.githubusercontent.com/13453967/33697586-54130e80-dacd-11e7-9e01-38f6eaed8eac.png)

![image](https://user-images.githubusercontent.com/13453967/33697590-5746b034-dacd-11e7-9120-c3dcf69a68da.png)


I'll keep working on this in the background, and I'll update with any major developments, but since this is taking way longer than I expected, I thought I'd share my current progress.

Thanks

**Comment by coreyeng** [comment]
Also, @ginty, if you still really dislike the name component, I can change it. I had already started this though so I just kept going with it.

**Comment by ginty** [comment]
Here's the diff: https://github.com/Origen-SDK/origen/compare/master...coreyeng:components

**Comment by coreyeng** [comment]
Added in PR #215
