### ISSUE TITLE
Chip modes interaction between DUT and child IP

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#146]
Hi,

What is the best way to set a DUT chipmode and have child IP 'receive' the broadcast and change their attributes?  The [chip mode API](http://origen-sdk.org/origen/guides/models/modes/#Mode) allows attributes to be added to the mode itself but would seem isolated from the rest of the chip IP.  I could go setup modes that mirror the DUT mods in every IP I want to interact with but wouldn't I currently be limited to manually initiating a mode change with every IP?  IMO, it would be great if all of the SubBlocks just 'listened' to mode broadcasts from the DUT and acted accordingly.  Let me know if this is already possible and I am missing something.

thx

**Comment by ginty** [comment]
Looks like the current mode is implemented locally within each model (sub_block):

https://github.com/Origen-SDK/origen/blob/master/lib/origen/model.rb#L174

I don't think we should actively listen for a change of mode, but rather fall back to picking up the parent's mode if no mode is defined. That would ultimately mean that every block would pick up the top-level mode if not otherwise defined.

Un-tested, but something like this should probably do what you want:

~~~ruby
def current_mode
  if @current_mode
    return _modes[@current_mode] if _modes[@current_mode]
    fail "The mode #{@current_mode} of #{self.class} has not been defined!"
  else
    parent.current_mode unless top_level?
  end
end
alias_method :mode, :current_mode
~~~

**Comment by info-rchitect** [comment]
handled [here](https://github.com/Origen-SDK/origen/pull/150)
