### ISSUE TITLE
Examples of rake commands used in Origen?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#155]
Hi,

Would anyone be willing to share some examples of how rake is used within the Origen ecosystem?

thx

**Comment by ginty** [comment]
Pretty much not at all.

I have never liked rake and any time I have tried to use it for anything non-trivial I have found it awkward (just try giving it a command line arg), un-intuitive and frankly a bit weird from a Ruby convention perspective.

I always thought I must be missing something though since it was used quite a lot within the rails community and so I built similar functionality into Origen.

However, in recent versions of rails they have moved all command operations which used to be under rake to under the rails command instead. That too always felt a bit weird why some commands were `rake blah` and some were `rails blah`.

So my advice would be, if you don't already use rake then don't start now, use origen application/plugin commands to implement whatever you have in mind.

**Comment by info-rchitect** [comment]
@ginty so why the tasks implementation then?  I am looking at building our pattern bursts by consuming an external file.  where does that sort of thing fit within Origen?

**Comment by ginty** [comment]
> I always thought I must be missing something though since it was used quite a lot within the rails community and so I built similar functionality into Origen.

Just never taken it back out, and hard to now anyway in case anyone does use it.

> I am looking at building our pattern bursts by consuming an external file. where does that sort of thing fit within Origen?

Either a custom command added to your application, or an override of the generate command. Rake is not going to do anything special to help you with that.

Are you trying to implement something similar to which we did in DN where you could say:

~~~
origen g some_3rd_party_format.blah
~~~

If so I can give you some pointers about how to create an integration like that.

**Comment by info-rchitect** [comment]
ok thanks
