### ISSUE TITLE
Validating Origen on JRuby

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#164]
Hi,

Has anyone used Origen with [JRuby](http://jruby.org/)?  The reason I ask is that Advantest SmarTest 8 is Java based and validating Origen on JRuby may provide a tighter integration with that ATE stack.

thx

**Comment by ginty** [comment]
I haven't, but I've thought about it, but I've always felt that Origen + JRuby are not really a good fit.

JRuby and JVM languages/applications in general are more suited to long running processes, think web servers and GUI apps, rather than command line applications like Origen where the user is continually running short running processes which you want to boot and start as quickly as possible.

Under JRuby, you would need to eat the JVM startup time at every Origen invocation - I don't know how long that really is these days but I think it would be noticeable.

Having said that, I have been keeping an eye on a project called TruffleRuby, which would give you the Java library integration you are thinking of, while solving the startup time problem.
It also boasts some impressive speed improvements which will make it a really compelling way to run Origen once they get it fully working.

Form the start of this year: https://lists.ruby-lang.org/pipermail/jruby/2017-January/000511.html

**Comment by info-rchitect** [comment]
OK thanks @ginty.
