### ISSUE TITLE
General steps for an test engineering application release?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#179]
Hi,

Does anyone have a general list of things that need to be done when releasing a new version of a test engineering app that creates test program flows and collateral (read compiler stuff)?  We are new to using Origen for test flows and would like to start 'doing it the right way' so we have app versions, improved quality control, web docs for test flows, etc.

thx

**Comment by ginty** [comment]
Would be better as a SO question

**Comment by info-rchitect** [comment]
@ginty I did think about that but I was warned multiple times not to ask questions that do not have something to do with coding.  I worry about losing my privilege to ask questions :/

**Comment by ginty** [comment]
I don't see any comments to that effect in any of our questions, so don't think we need to be too concerned about one or two over-zealous mods.
As long as you frame your question in such a way as to fit in with these guidelines it should be fine: https://stackoverflow.com/help/on-topic

At the end of the day though, if we can't use SO to ask questions then we will need to look somewhere else.

I don't think this is a good place though since as soon as it is closed it disappears from view and I don't think these are ranked to high by Google - I very rarely find my way to a Github issue via searching for a question.

This is a good question, but I would rather spend the time on an answer which will contribute to the available documentation/help pool, and this is not the place for that.

**Comment by ginty** [comment]
We do also have these forums set up, though we haven't used them so far:

https://disqus.com/home/channel/origensdk/

https://www.reddit.com/r/OrigenSDK/

Potentially one of these might be better for some questions, especially if they are likely to involve discussion and more related to process. SO definitely do prefer the 'How do I do this...' style of question, though to be fair this particular one we are discussing could probably be phrased in that way.

**Comment by info-rchitect** [comment]
@ginty I do appreciate the predicament.  Let me take a shot at asking it on S.O.  Not sure my team wants to open any more accounts :)

**Comment by info-rchitect** [comment]
https://stackoverflow.com/questions/47574257/how-to-check-origen-app-creates-known-good-flows-correctly
