### ISSUE TITLE
User install dir invocation keeps running bundle

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/origen#192]
I tried to set up a user Origen install dir for the first time so that I could do some development of a global command.

I created a new directory inside of which I want `origen` invocations to launch my user installation instead of my usual tools installation.

Inside this directory I added my own site config:

~~~
/home/nxa21353/Code/my_origen/origen_site_config.yml
~~~

and it contains only these lines:

~~~yaml
user_install_enable: true
user_install_dir: /home/nxa21353/Code/my_origen/.origen
~~~

When invoking origen within the `my_origen` directory it successfully built my user install where I want it and it seems to be getting invoked.

However, every time I run `origen` it does another bundle install every time:

~~~
[nxa21353@acv0082 my_origen]$ origen -v
Installing required gems...
...
...
Using rspec-legacy_formatters 1.0.1
Using origen 0.28.2
Bundle complete! 1 Gemfile dependency, 57 gems now installed.
Bundled gems are installed into /home/nxa21353/.origen/gems.
     Origen: 0.28.2
~~~

Note that it seems to be installing the gems into my original gem directory, which I don't think is correct, though it is ultimately overriding the version of Origen from my tool install and giving me the one from my user install.

My tool origen is:

~~~
[nxa21353@acv0082 Code]$ origen -v
     Origen: 0.24.0
~~~

**Comment by coreyeng** [comment]
Hello. Actually, I've been meaning to discuss this with you as well...

I noticed this too, but it doesn't replicate if you source your own Origen beforehand. For example, during development, I'd source <my Origen development workspace>/bin/origen directly, and I don't see this issue.

This is also true of the 'first-bundle-fail' issue (if you noticed, Bundle fails with some exception the first time you build the new gem location, but its fine after subsequent runs and even updates alright).

I will try to replicate this again locally, but I think it may be somewhere upstream in the system-wide setup, which is difficult to debug since I don't have permissions to make any changes. We can discuss this internally though and then update this issue with any findings.

**Comment by ginty** [comment]
I see what you mean, I'll look into it...

**Comment by coreyeng** [comment]
@ginty okay to close this issue?
