### ISSUE TITLE
Origen stance on Autoload

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#204]
Hi,

As Origen moves toward v1.0 I was hoping to get the official Origen stance on Autoload.  There are links that show [Matz essentially disowning Autoload](https://bugs.ruby-lang.org/issues/5653).  Origen uses autoload extensively but Autoload does not work with multi-threading, or guaranteed to work with it. 

Is Autoload something Origen will continue to use on v1.0 or will other new requirements change the use case for Autoload?  We are looking at converting our app to Autoload and thought this thread might help us make our decision.

regards

**Comment by ginty** [comment]
I think it is fine to use.

The concerns around it are to do with multi-threading, but all Origen apps are single threaded today with no real plans to change that (I have a vague notion that it might be used to implement concurrent pattern creation in the future, but no real plans to work on it anytime soon).

A quick search shows that it is used heavily in the most famous Ruby platform too: https://github.com/rails/rails/search?utf8=%E2%9C%93&q=autoload&type=

The problem is that autoload does provide a useful feature - prevent an application from requiring the entire world at boot up time and slowing down its startup accordingly.
If the Ruby team really want to deprecate/remove autoload in future then they will need to come up with an alternative solution that provides the same benefits. Or just fix whatever is the current issue with autoload under certain circumstances.

Here is my guidance on when to use autoload:

- Top-level apps shouldn't worry about it at all, just use the wildcard require that is already setup in new Origen applications.
- Small or seldom used plugins shouldn't need to worry about it either.
- Large plugins with many files that are widely used, think OrigenTesters for example, should try to be good citizens and use autoload.

**Comment by ginty** [comment]
Just noticed that actually rails re-implements autoload, so that's always an option that we could do within Origen - for example to globally make it equivalent `require` if that was something we needed to do in order to migrate to Ruby 3.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies/autoload.rb

**Comment by info-rchitect** [comment]
OK thanks @ginty.
