### ISSUE TITLE
Untracked files broke tagging process

### ISSUE THREAD

**Issue by ThaoHuynhFsl** [Origen-SDK/origen#22]
The rc tag will update the version and release note history before "git commit -m "Updated app version and history"

if there are untracked files the git commit with update app version will stop with error

On branch develop
Your branch is ahead of 'origin/develop' by 1 commit.
(use "git push" to publish your local commits)
Untracked files:

so nothing had commit or push but version and release note already got update.  I have to manually update version and and remove note from release then remove untracked file and running tag again.

Probably rc tag need to change the order to run git commit update app version first or checking for untracked files before update version and release note.

Thanks,
Thao Huynh

**Comment by ginty** [comment]
Hi Thao,
I believe this is fixed by this commit:
https://github.com/Origen-SDK/origen/commit/f52515aef54001a31c0b130d9231790d59ea7f31#diff-12e7cbb75850e67b79ee09f62e7e16c4

I think the issue was that it was treating un-tracked files as changes pending commit and this screwed up the release process.

If you make a similar change to RGen please update here to confirm if it fixes it.

Thanks!
