### ISSUE TITLE
Dynamic test flow comments

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#220]
Hi,

We have a resource to tackle this [stack overflow discussion](https://stackoverflow.com/questions/48322364/adding-dynamic-content-to-test-flow-comments).  Should we support both string interpolation in the comment parser and 'cc' dynamic method, or just pick one?  Also, does anyone have a general walk-through of the code architecture affecting this type of PR?

thx

**Comment by ginty** [comment]
Hi @info-rchitect,

Thanks for picking this up, here are some pointers...

If we are going the `cc` route then there is no need for any special dynamic interpolation handling, if you don't need to inject variable data then just use the regular Ruby comments, if you do then you use the `cc`. The `cc` will be evaluated at flow execution time, so you will be able to inject any dynamic variables you like:

~~~ruby
dut.atds.each_with_index do |atd, i|

  cc "Functionally test ATD#{i}"
  func :atd_test, instance: i

end
~~~

`cc` is an existing global method that is commonly used to annotate test patterns, I think it makes intuitive sense to re-use that here rather than introduce another method.
The existing `cc` implementation is here: https://github.com/Origen-SDK/origen/blob/master/lib/origen/global_methods.rb#L8

So we want to hi-jack the comments there and forward it to our test program comment store (once we implement it), you can identify when the program generator is running via:

~~~ruby
if Origen.tester.generating == :program
  # Handle a prog gen comment
else
  # Existing patgen comment handling
end
~~~

The program (and pattern) generation logic is still somewhat split between Origen (where it originally lived), and OrigenTesters (OT), though the majority of it is now in OT and we want to ensure that any new stuff we are adding goes in there.

The way that the current comment system works is that the program flow source file is parsed for comments when `Flow.create` is encountered, and placed into a comment stack, that is done here: https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/origen_ext/generator/flow.rb#L25

... 10 minutes pass as I try to figure out how this works...

The comments in the stack get consumed here: https://github.com/Origen-SDK/origen_testers/blob/5b89bf287b3d307bd6708c878666f3609a5fd3af/lib/origen_testers/flow.rb#L357

However!

I see now that the way this is implemented is that it transfers the comments into the options hash (as originally passed from your test program flow file) under the key `:description`.

So actually, this would probably already work today:

~~~ruby
test :my_test, description: ["This test blah blah blah", "Does something blah blah"]
~~~

That's pretty ugly though, so might still be worth adding support for:

~~~ruby
cc "This test blah blah blah"
cc "Does something blah blah"
test :my_test
~~~

So it would really just be a case of storing what is passed to `cc` into an array somewhere, and then injecting it into the `:description` option in the same way as it is done above if the "cc buffer" contains some comments.

Hope that helps get you started, obviously come back with questions as required.

**Comment by info-rchitect** [comment]
@ginty that should be more than enough to get this completed.   thx!

**Comment by info-rchitect** [comment]
@CodyBriscoe

**Comment by info-rchitect** [comment]
moved to [here](https://github.com/Origen-SDK/origen/issues/223)
