### ISSUE TITLE
Cannot add atlassian-stash gem to app due to highline gem conflict

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#230]
Hi,

I am trying to add the [atlassian-stash gem](https://rubygems.org/gems/atlassian-stash/) to my app and I get the following bundler conflict.

~~~shell
Bundler could not find compatible versions for gem "highline":
  In Gemfile:
    atlassian-stash (~> 0.7.0) was resolved to 0.7.0, which depends on
      commander (~> 4.1.2) was resolved to 4.1.2, which depends on
        highline (~> 1.6.11)

    sg4 was resolved to 0.1.0, which depends on
      origen was resolved to 0.31.0, which depends on
        highline (~> 1.7)
~~~

I will contact the commander gem folks about changing their dependencies but does anyone know if we need highline  1.7?  Secondly, does anyone think adding this gem as a default gem in Origen makes sense given the popularity of stash?

thx

**Comment by welguisz** [comment]
First highline gem is needed for IO.  Instead of having gets and puts, you can just use it to ask questions and validate it automatically.  I am thinking that _origen new_ is where highline is needed.

As for atlassian-stash, it looks like it was last updated in November 2015.  I would consider this a zombie project.  As for what it does, I don't see a reason for it to be a part of the baseline Origen Gem.

[Atlassian-stash Documentation](http://www.rubydoc.info/gems/atlassian-stash/0.7.0)

**Comment by info-rchitect** [comment]
@welguisz yeah i saw that there was some activity in general around the gem this year but I agree that itis not ready for primetime.
