### ISSUE TITLE
Cannot create a parameter set attribute called 'path'

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#303]
Hi,

Found a corner case bug where it is impossible to create a parameter set attribute called 'path'.

~~~ruby
        define_params :cant_use_path do |p|
          p.path = 'my path'
        end
~~~

Here are the rspec interactive results:

~~~ruby
[1] pry(#<RSpec::ExampleGroups::Parameters>)> dut.params.contexts
=> [:default, :cant_use_path, :ate, :probe, :ft, :set1, :set2, :set3]
[2] pry(#<RSpec::ExampleGroups::Parameters>)> dut.params(:cant_use_path)
=> {}
~~~

I believe this may be related to the fact that 'path' has a meaning in the scope of the parameter set and is being ignored versus being overridden with the value put in the parameter set definition.  Any ideas?

thx

**Comment by ginty** [comment]
Looks like it is because the `Origen::Parameters::Set` class, an instance of which is assigned to `p` in your example, has an attribute called `path`: https://github.com/Origen-SDK/origen/blob/master/lib/origen/parameters/set.rb#L6

So a parameter called `name`, `top_level` or in fact named after any of the methods defined by that class wouldn't work either.

I haven't tried it, but it looks like this should work for such parameters:

~~~ruby
define_params :cant_use_path do |p|
  p[:path] = 'my_path'
end
~~~

I don't think there is any way to make the original API work as you have written it, unless you wanted to try a heroic refactor to rename all of the `Origen::Parameters::Set` classes attributes and methods to start with an underscore or something to avoid naming collisions like this.

Or alternatively we (and by that I mean you :-) add something like a `set` method and make this the recommended way to define parameters instead:

~~~ruby
define_params :cant_use_path do |p|
  p.set(:path, 'my_path')
end
~~~

**Comment by info-rchitect** [comment]
Added spec test for this in [this PR](https://github.com/Origen-SDK/origen/pull/369)
