### ISSUE TITLE
How Origen handles PATH

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#329]
Hi,

As I convert us to the new Origen, I see we need to set './lbin' to the user PATH.  A couple of questions:

1.  Should Origen ask users to do this or should Origen just run its commands with an augmented PATH?
2. Has anyone setup a symlink at the top of their app so users didn't have to change their PATH?  
    `bundle -> lbin/bundle`
3. How do Windows users handle the bundle executable?

thx

**Comment by ginty** [comment]
This has always been part of the Origen installation instructions, the only thing that has been added here is a check/warning that a user's environment actually does it.

On Windows it should be the same, though I notice now that we never actually mentioned it in that guide.

However, as is evident from your comment, it mostly works without this. If you don't have it, it means that when you run 'origen' you are not initially launching from the Origen version that is bundled in your application. Instead it launches the Origen version that is installed to the system Ruby, but it works OK because Origen's boot system will identify this situation and silently re-launch using the bundled Origen.

Other gems won't do this though, so without 'lbin' in your PATH you could get weird errors if your application or Origen tries to launch 3rd party executables.
Potentially, you could end up running a different version of the gem than you think you are - best case that's OK because they are feature compatible, worst case it is not or else you get weird Bundler errors about different Gem versions being activated.

Examples of Origen command where this could crop up would be 'origen web compile' which calls `system('nanoc')` or `origen specs` which calls `system('rspec')`.

Unfortunately, I don't believe that there is an easy way to take care of this in Ruby code. The only thing that might partially work would be if we changed all such system calls to be `system("#Origen.root}/lbin/<executable>")`, but it would be impossible to guarantee that we got them all across plugins too.

I am open to suggestion here, is it better to allow users to be oblivious to this?

**Comment by info-rchitect** [comment]
@ginty We put a symlink to lbin/bundle in our top level app, though that would not work for Windows users.  That seems to work for Linux folks.  I don't think we need to refactor a bunch, just wanted to see what folks thought.

**Comment by pderouen** [comment]
I'd be in favor of removing the .\lbin from the path and updating origen to use the path from Origen.root.

Could we download all of the public apps and have a script look for "system(" and things bound by `command`?

**Comment by pderouen** [comment]
...apparently \` means something in markdown.  \`some_command\` is the other way to execute a system command.

**Comment by ginty** [comment]
Actually, I misspoke, that's actually not a problem since Bundler overrides the native Ruby shell commands to prepend the current bundle environment, so as long as your inside an Origen invocation all will be well - https://bundler.io/man/bundle-exec.1.html#Shelling-out

Therefore, it's really only an issue if users try to launch a 3rd party executable themselves - `origen` and `bundle` are both OK because they both have the smarts to always resolve to the bundled version, but something like 'rspec' would not.

Maybe its not worth warning for just that case though?

I suppose a user doing that might be smart enough to know to try `bundle exec rspec` or `./lbin/rspec` if they came across an issue.

**Comment by pderouen** [comment]
Yeah, if that's the case it's not worth warning.

**Comment by ginty** [comment]
OK, I agree to remove this new warning, including in #330
