### ISSUE TITLE
Can we remove Ruby 2.2 dependencies from app generators?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#410]
Hi,

This line causes issues with newer gems:

~~~ruby
gem 'byebug', '<9.1.0' # This version restriction required if you need Ruby < 2.2, otherwise you can remove it
~~~

Can we remove this from the app generator code?  We don't support Ruby 2.2 in our Github builds so no need to keep it around right?

thx

**Comment by pderouen** [comment]
I vote that our app generator not cause dependency issues out of the shoot. I think we're recommending Ruby >=2.6 now aren't we?

**Comment by ginty** [comment]
No issue from me to change this, as long as it stays compatible with Ruby 2.5 (our min supported version) out the box.

**Comment by info-rchitect** [comment]
How would we really test this besides `origen test`?

**Comment by ginty** [comment]
We probably don't have to, we're moving in step with Ruby and it's community in terms of our minimum supported version.
So we can safely assume that an unspecified version of Byebug will resolve to something that works.

As an aside, I just moved O2 onto Github Actions instead of Travis for CI and its *much* simpler to setup. It wouldn't be hard to setup an automated test on GA that would build a new app and make sure it boots.

I can give a quick overview of GA at the next core team.

**Comment by info-rchitect** [comment]
https://github.com/Origen-SDK/origen_app_generators/pull/11

**Comment by priyavadan** [comment]
@info-rchitect can we close this issue ?
