### ISSUE TITLE
93k interface docs

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#94]
Hi,

From the [guides](http://origen-sdk.org/origen/guides/program/v93k/), the second line of code doesn't seem to work.  Perhaps I am missing the context, in that, the 'origen' method need to be created somewhere/somehow else?

~~~ruby
t = test_suites.add(:vreg_func, tim_equ_set: 15, tim_spec_set: 1, timset: 1, lev_equ_set: 20)
t.test_method = test_methods.origen.functional_test(check_shutdown: 1)
~~~

thx

**Comment by ginty** [comment]
Sorry, that guide is still a work in progress.

The convention on the V93K these days is to define your own test methods rather than using the basic ones supplied by Advantest (which they no longer recommend you to use).
You can define what the arguments to your own test methods are using the API shown here: http://origen-sdk.org/testers/release_notes/#v0_3_0_pre38

We are still in the very early stages, but we want to define an Origen test method library to fill the void left by the lack of an Advantest library, that is what is being used in your example.

**Comment by info-rchitect** [comment]
HI Ginty,

I tried what you suggested with no luck. I also checked the release notes for 'StdLib' and didn't see any reference.

~~~ruby
module STP
  class Interface
    include OrigenTesters::ProgramGenerators
    include OrigenStdLib
~~~

Here is what I got in the console:

~~~shell
peologin01:stp $ origen p program/ws1.rb -e v93k

COMPLETE CALL STACK
-------------------
There was an error while trying to load the gem 'stp'.
Gem Load Error is: uninitialized constant STP::Interface::OrigenStdLib
Did you mean?  OrigenSWD
~~~

**Comment by ginty** [comment]
Did you add the gem to your Gemfile?

~~~ruby
gem "origen_std_lib"
~~~

**Comment by info-rchitect** [comment]
OK yeah little slow today.  what version for a gemspec file?

**Comment by ginty** [comment]
Looks like the latest version is 0.10.0, though you can just leave the version out and it will pick up the latest
