### ISSUE TITLE
Gap between site config file and the app session store

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#99]
Hi,

My app and the accompanying gems are meant to serve any product that is configured in a YAML config file.  Upon app load I load the YAML config information with the [configatron gem](https://rubygems.org/gems/configatron/versions/4.5.0) and set session stores.  Here is an example of one of the product configurations.  The idea here is that any app or plugin can add relevant information they need to service the product.

~~~yaml
:products:
  :myprod:
    :name: 'My Awesome product'
    :family: :awesome_soc
    :revisions:
      :ao:
        :db_aliases:
          operA: '800'
          operB: '800'
          operC: '800'
        :metadata:
          mbist: 'myprod_revA0_mbist_meta.csv'
          scan: 'myprod_revA0_scan_meta.csv'
          registers: 'path/vault to my registers source'
          pins: 'path/vault to my pins source'
      :b0:
        :db_aliases:
          operA: '801'
          operB: '801'
          operC: '801'
        :metadata:
          mbist: 'myprod_revB0_mbist_meta.csv'
          scan: 'myprod_revB0_scan_meta.csv' 
          registers: 'path/vault to my registers source'
          pins: 'path/vault to my pins source'
~~~

So here are my questions:

1.  Should the Origen site config file fill this purpose?
2. Should the app session store allow users to add in data via their own YAML files
3. Why isn't the site config information already stored in the session store?

I would like to get rid of using configatron (great gem but very similar to the native session store).

thanks!

**Comment by ginty** [comment]
_Should the Origen site config file fill this purpose?_

No, the site config is intended to provide a mechanism for a company to configure the Origen core platform to work within its particular Linux compute environment.

_Should the app session store allow users to add in data via their own YAML files_

The session store is intended to provide applications with a mechanism to persist temporary data across Origen invocations so that they don't have to create their own system of saving data to local files. Think user passwords, a record of what version of some 3rd party data that the user has checked out, etc.

_Why isn't the site config information already stored in the session store?_

They are not really related concepts.


Configuring DUT attributes via a YAML file is an interesting concept, but I'm not sure what the advantages to that are over a Ruby-based approach?

The more conventional way to do this would be either via passing values from the target:

~~~ruby
class MyDUT
  include Origen::TopLevel

  attr_accessor :operA, :operB
  attr_accessor :mbist
end

# target/a0.rb
MyDUT.new operA: '800', operB: '800',
          mbist: 'myprod_revA0_mbist_meta.csv'

# target/b0.rb
MyDUT.new operA: '801', operB: '801',
          mbist: 'myprod_revB0_mbist_meta.csv'
~~~

I don't really like having too much data in the target and prefer to push it all down to the model, so either you can have separate child classes per device:

~~~ruby
class A0 < MyDUT
  def initialize(options = {})
    @operA = '800'
    @operB = '800'
    @mbist = 'myprod_revA0_mbist_meta.csv'
  end
end

class B0 < MyDUT
  def initialize(options = {})
    @operA = '801'
    @operB = '801'
    @mbist = 'myprod_revB0_mbist_meta.csv'
  end
end

# target/a0.rb
A0.new

# target/b0.rb
B0.new
~~~

Or you can have a single model class and pass a configuration attribute from the target:

~~~ruby
class MyDUT
  include Origen::TopLevel

  attr_accessor :operA, :operB
  attr_accessor :mbist

  def initialize(options = {})
    if options[:configuration] == :a0
      @operA = '800'
      @operB = '800'
      @mbist = 'myprod_revA0_mbist_meta.csv'
    elsif options[:configuration] == :a0
      @operA = '801'
      @operB = '801'
      @mbist = 'myprod_revB0_mbist_meta.csv'
    else
      fail "No valid configuration supplied!"
    end
  end
end

# target/a0.rb
MyDUT.new configuration: :a0

# target/b0.rb
B0.new configuration: :b0
~~~

**Comment by info-rchitect** [comment]
HI Ginty,

I actually did exactly what you coded regarding the configuration option in the target file.  Any it works perfectly.  It really comes down to how best to get the community to keep this information updated and fresh. Many of the people who own these information assets do not code or code Ruby.  Also, this information should be typed by someone only once so a site level config file seemed a good choice.  Not sure if you remember but this all is designed to hook up with Cross-Origen where the user sets a target product and it gets instantiated as the 'current product' via a SubBlocks module vs a hardcoded, named class.

~~~ruby
MyApp::Product.new(:my_prod, rev: :a1)
~~~

Then in my app I have a generic Product class that handles syncing information from the YAML config file and then goes and gets data using Cross-Origen.

~~~ruby
module MyApp
  class Product
    include Origen::TopLevel
    include Config
    
    attr_accessor :nick, :family, :revision, :name, :config

    def initialize(nick, options = {})
      options = {
        rev: :a0
      }.update(options)
      @nick = nick
      @revision = options[:rev]
      fail unless product_valid?
      load_product_config
      set_session_store
    end
    
    private
    
    def product_valid?
      return_val = true
      if configatron.products.has_key? @nick
        @name = configatron.products[@nick].name
        unless configatron.products[@nick].revisions.has_key? @revision
          Origen.log.error("Cannot locate a revision for product '#{@name}'")
          return_val = false
        end
      else
        Origen.log.error("Cannot locate a product by the nickname '#{@nick}'")
        return_val = false
      end
      return_val
    end
    
    # Set the current product info in the session store so all gems can see important info
    def set_session_store
      Origen.app.session.nemawashi[:product] = @nick
      Origen.app.session.nemawashi[:product_revision] = @revision
      Origen.app.session.nemawashi[:product_name] = @name
      Origen.app.session.nemawashi[:product_family] = @family
    end
    
    # Load product configuration data
    def load_product_config
      @config = configatron.products[@nick]
      @family = configatron.products[@nick].family
    end
  
  end
end
~~~

I broadcast the product information via the session store so other gems can check the YAML config file for their specific bits of product-related data.  The product YAML config file should not store information that should be part of the model, rather it is meant to store product-related data that isn't part of the actual device.  In the YAML example, you can see that I store a database alias that I do not own.  I guess I didn't want folks having to touch my models just to give me that piece of information.  There is definitely not one single way to do this, thanks for the good discussion.  It made me realize I need to be very clear about what information should go into the YAML config file.  If I see folks adding in information like the size of the L3 SRAM then I will have to tighten it down.

regards

**Comment by ginty** [comment]
Seems like a good system, and yes especially if you want these configs to be maintained by a 3rd party who doesn't know Origen.

Definitely the site config is not the place for these though.
You could either wrap them in a plugin and distribute it to all your apps that way, or if you don't want the Origen overhead, you can just check them into source control and use the remotes system to import them into your apps: http://origen-sdk.org/origen//guides/misc/remotes/

**Comment by info-rchitect** [comment]
thanks again for the help with the design aspect of Origen-SDK.
